main: ${project.groupId}.${project.name}
name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [Cayorion]
depend: [MassiveCore]
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
permissions:
  massivehat.use: {description: wear any block as a hat, default: false}
