main: com.massivecraft.massivehat.MassiveHat
name: MassiveHat
version: 2.8.20
website: https://www.massivecraft.com/massivehat
depend: [MassiveCore]
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
permissions:
  massivehat.use: {description: wear any block as a hat, default: false}
  massivehat.waruse: {description: wear any block as a hat in war-arenas, default: false}
