name: MassiveHat
version: 2.8.13
main: com.massivecraft.massivehat.MassiveHat
depend: [MassiveCore]
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
permissions:
  massivehat.use: {description: wear any block as a hat, default: false}
  massivehat.waruse: {description: wear any block as a hat in war-arenas, default: false}
